### ISSUE TITLE
New `'fileIds': [file.file_id for file in files]` is mandatory?

### ISSUE THREAD

**Issue by fotoente** [yupix/MiPAC#8]
**Describe the bug**
When starting the bot and sending the first "Bot started!" message via the API into Misskey the error as below shows up and no message is sent.

**Code snippets**
```python
    async def on_ready(self, ws):
        await Router(ws).connect_channel(["global", "main"])  # Connect to global and main channels
        await self.client.note.action.send(content=datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " $[rotate.deg=180 :blobfox:] Bot started!", visibility="specified") #  <- is an argument missing here?
        self.loop12h.start()  # Launching renew emojis every 12 hours
        self.loop1h.start()  # Launching posting every hour
```

**To Reproduce**
Install latest MiPA & MiPAC
Start Bot

**Expected behavior**
Message "Bot started" should appear as a DM in the prfile where the message is created.

**Screenshots**
```
Traceback (most recent call last):
  File "/home/ente/git/Misskey-Bot-CeilingFox/venv/lib/python3.10/site-packages/mipa/ext/commands/bot.py", line 222, in _run_event
    await coro(*args, **kwargs)
  File "/home/ente/git/Misskey-Bot-CeilingFox/cfbot.py", line 41, in on_ready
    await self.client.note.action.send(content=datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " $[rotate.deg=180 :blobfox:] Bot started!", visibility="specified")
  File "/home/ente/git/Misskey-Bot-CeilingFox/venv/lib/python3.10/site-packages/mipac/actions/note.py", line 141, in send
    'fileIds': [file.file_id for file in files]
```

**Environment used:**
 - OS: Linux, with an venv
 - Python: 3.10.5
 - MiPAC: MiPA 0.0.2; MiPAC 0.1.0 (freshly installed 15:30 CEST; 13:30 UTC)

**Comment by yupix** [comment]
The problem was caused by a change in 894c0b39d7b464f340d1b112614c6652711cac6d. We have fixed it, please try again. We apologize for the inconvenience.
